// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2vJWtZeWmGklRmT4H8l8sB0KaR8CXSgA',
    appId: '1:59678935940:web:c91584c1295a288e2a6bd1',
    messagingSenderId: '59678935940',
    projectId: 'srp-lanske-web-dev',
    authDomain: 'srp-lanske-web-dev.firebaseapp.com',
    storageBucket: 'srp-lanske-web-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWN8LSenfqfozR1uTcthjNisu4ehSGNXQ',
    appId: '1:59678935940:android:223d8ed753bcc1a12a6bd1',
    messagingSenderId: '59678935940',
    projectId: 'srp-lanske-web-dev',
    storageBucket: 'srp-lanske-web-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXxwt3tpVWkJ2wMcbtIgFoD0kTLO0bp40',
    appId: '1:59678935940:ios:b3a27b5d099b35b32a6bd1',
    messagingSenderId: '59678935940',
    projectId: 'srp-lanske-web-dev',
    storageBucket: 'srp-lanske-web-dev.firebasestorage.app',
    iosBundleId: 'com.example.srpLanske',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXxwt3tpVWkJ2wMcbtIgFoD0kTLO0bp40',
    appId: '1:59678935940:ios:b3a27b5d099b35b32a6bd1',
    messagingSenderId: '59678935940',
    projectId: 'srp-lanske-web-dev',
    storageBucket: 'srp-lanske-web-dev.firebasestorage.app',
    iosBundleId: 'com.example.srpLanske',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2vJWtZeWmGklRmT4H8l8sB0KaR8CXSgA',
    appId: '1:59678935940:web:6e6aeb357dc2feb52a6bd1',
    messagingSenderId: '59678935940',
    projectId: 'srp-lanske-web-dev',
    authDomain: 'srp-lanske-web-dev.firebaseapp.com',
    storageBucket: 'srp-lanske-web-dev.firebasestorage.app',
  );
}
